name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file NextFlow/Dockerfile --tag wombatp/transproteomics-pipeline:dev
    - name: Push Docker image to DockerHub (dev)
      run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push wombatp/transproteomics-pipeline:dev
