name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
      CAPSULE_LOG: none
    strategy:
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['20.04.0', '']
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      working-directory: Nextflow
      run: docker build . --file Dockerfile --tag wombatp/transproteomics-pipeline:dev

    - name: Push Docker image to DockerHub (dev)
      run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push wombatp/transproteomics-pipeline:dev

    - name: Pull docker image
      run: |
          docker pull wombatp/transproteomics-pipeline:dev

    - name: Install Nextflow
      run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

    - name: Run pipeline with test data
        working-directory: Nextflow
        # For example: adding multiple test runs with different parameters
        # Remember that you can parallelise this by using strategy.matrix
      run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker
